//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToeMBT.TestSuite {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3146.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GameBoardTestSuite : VsTestClassBase {
        
        public GameBoardTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion

        /*
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS0() {
            this.Manager.BeginTest("GameBoardTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("executing step \'call Move4(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(2, 2);
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call Move5(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 0);
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S11
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS11() {
            this.Manager.BeginTest("GameBoardTestSuiteS11");
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Comment("executing step \'call Move7(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 0);
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Comment("executing step \'call Move8(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 1);
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Comment("executing step \'call Move9(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move9(0, 1);
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("checking step \'return Move9\'");
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S113
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS113() {
            this.Manager.BeginTest("GameBoardTestSuiteS113");
            this.Manager.Comment("reaching state \'S113\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S114\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S115\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S116\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S117\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S118\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S119\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S120\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S121\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S122\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S123\'");
            this.Manager.Comment("executing step \'call Move6(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 1);
            this.Manager.Comment("reaching state \'S124\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S125\'");
            this.Manager.Comment("executing step \'call Move7(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 0);
            this.Manager.Comment("reaching state \'S126\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S127\'");
            this.Manager.Comment("executing step \'call Move8(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 2);
            this.Manager.Comment("reaching state \'S128\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S129\'");
            this.Manager.Comment("executing step \'call Move9(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move9(2, 2);
            this.Manager.Comment("reaching state \'S130\'");
            this.Manager.Comment("checking step \'return Move9\'");
            this.Manager.Comment("reaching state \'S131\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S132
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS132() {
            this.Manager.BeginTest("GameBoardTestSuiteS132");
            this.Manager.Comment("reaching state \'S132\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S133\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S134\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S135\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S136\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S137\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S138\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S139\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S140\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S141\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S142\'");
            this.Manager.Comment("executing step \'call Move6(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 1);
            this.Manager.Comment("reaching state \'S143\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S144\'");
            this.Manager.Comment("executing step \'call Move7(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 0);
            this.Manager.Comment("reaching state \'S145\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S146\'");
            this.Manager.Comment("executing step \'call Move8(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(2, 2);
            this.Manager.Comment("reaching state \'S147\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S148\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S149
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS149() {
            this.Manager.BeginTest("GameBoardTestSuiteS149");
            this.Manager.Comment("reaching state \'S149\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S150\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S151\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S152\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S153\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S154\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S155\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S156\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S157\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S158\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S159\'");
            this.Manager.Comment("executing step \'call Move6(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 1);
            this.Manager.Comment("reaching state \'S160\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S161\'");
            this.Manager.Comment("executing step \'call Move7(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(2, 2);
            this.Manager.Comment("reaching state \'S162\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S163\'");
            this.Manager.Comment("executing step \'call Move8(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 0);
            this.Manager.Comment("reaching state \'S164\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S165\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S166
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS166() {
            this.Manager.BeginTest("GameBoardTestSuiteS166");
            this.Manager.Comment("reaching state \'S166\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S167\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S168\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S169\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S170\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S171\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S172\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S173\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S174\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S175\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S176\'");
            this.Manager.Comment("executing step \'call Move6(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 1);
            this.Manager.Comment("reaching state \'S177\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S178\'");
            this.Manager.Comment("executing step \'call Move7(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(2, 2);
            this.Manager.Comment("reaching state \'S179\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S180\'");
            this.Manager.Comment("executing step \'call Move8(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 2);
            this.Manager.Comment("reaching state \'S181\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S182\'");
            this.Manager.Comment("executing step \'call Move9(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move9(1, 0);
            this.Manager.Comment("reaching state \'S183\'");
            this.Manager.Comment("checking step \'return Move9\'");
            this.Manager.Comment("reaching state \'S184\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S185
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS185() {
            this.Manager.BeginTest("GameBoardTestSuiteS185");
            this.Manager.Comment("reaching state \'S185\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S186\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S187\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S188\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S189\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S190\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S191\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S192\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S193\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S194\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S195\'");
            this.Manager.Comment("executing step \'call Move6(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(2, 2);
            this.Manager.Comment("reaching state \'S196\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S197\'");
            this.Manager.Comment("executing step \'call Move7(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 2);
            this.Manager.Comment("reaching state \'S198\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S199\'");
            this.Manager.Comment("executing step \'call Move8(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 0);
            this.Manager.Comment("reaching state \'S200\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S201\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S202
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS202() {
            this.Manager.BeginTest("GameBoardTestSuiteS202");
            this.Manager.Comment("reaching state \'S202\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S203\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S204\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S205\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S206\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S207\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S208\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S209\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S210\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S211\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S212\'");
            this.Manager.Comment("executing step \'call Move6(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(2, 2);
            this.Manager.Comment("reaching state \'S213\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S214\'");
            this.Manager.Comment("executing step \'call Move7(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 2);
            this.Manager.Comment("reaching state \'S215\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S216\'");
            this.Manager.Comment("executing step \'call Move8(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 1);
            this.Manager.Comment("reaching state \'S217\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S218\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S219
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS219() {
            this.Manager.BeginTest("GameBoardTestSuiteS219");
            this.Manager.Comment("reaching state \'S219\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S220\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S221\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S222\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S223\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S224\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S225\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S226\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S227\'");
            this.Manager.Comment("executing step \'call Move5(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(0, 1);
            this.Manager.Comment("reaching state \'S228\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S229\'");
            this.Manager.Comment("executing step \'call Move6(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(2, 2);
            this.Manager.Comment("reaching state \'S230\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S231\'");
            this.Manager.Comment("executing step \'call Move7(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 1);
            this.Manager.Comment("reaching state \'S232\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S233\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S234
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS234() {
            this.Manager.BeginTest("GameBoardTestSuiteS234");
            this.Manager.Comment("reaching state \'S234\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S235\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S236\'");
            this.Manager.Comment("executing step \'call Move2(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(0, 1);
            this.Manager.Comment("reaching state \'S237\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S238\'");
            this.Manager.Comment("executing step \'call Move3(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(2, 2);
            this.Manager.Comment("reaching state \'S239\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S240\'");
            this.Manager.Comment("executing step \'call Move4(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 2);
            this.Manager.Comment("reaching state \'S241\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S242\'");
            this.Manager.Comment("executing step \'call Move5(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(1, 1);
            this.Manager.Comment("reaching state \'S243\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S244\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S245\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S246\'");
            this.Manager.Comment("executing step \'call Move7(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(0, 0);
            this.Manager.Comment("reaching state \'S247\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S248\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S249
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS249() {
            this.Manager.BeginTest("GameBoardTestSuiteS249");
            this.Manager.Comment("reaching state \'S249\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S250\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S251\'");
            this.Manager.Comment("executing step \'call Move2(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(0, 1);
            this.Manager.Comment("reaching state \'S252\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S253\'");
            this.Manager.Comment("executing step \'call Move3(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(2, 2);
            this.Manager.Comment("reaching state \'S254\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S255\'");
            this.Manager.Comment("executing step \'call Move4(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 2);
            this.Manager.Comment("reaching state \'S256\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S257\'");
            this.Manager.Comment("executing step \'call Move5(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(1, 1);
            this.Manager.Comment("reaching state \'S258\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S259\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S260\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S261\'");
            this.Manager.Comment("executing step \'call Move7(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(2, 0);
            this.Manager.Comment("reaching state \'S262\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S263\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S264
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS264() {
            this.Manager.BeginTest("GameBoardTestSuiteS264");
            this.Manager.Comment("reaching state \'S264\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S265\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S266\'");
            this.Manager.Comment("executing step \'call Move2(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(0, 1);
            this.Manager.Comment("reaching state \'S267\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S268\'");
            this.Manager.Comment("executing step \'call Move3(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(2, 2);
            this.Manager.Comment("reaching state \'S269\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S270\'");
            this.Manager.Comment("executing step \'call Move4(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 2);
            this.Manager.Comment("reaching state \'S271\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S272\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S30
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS30() {
            this.Manager.BeginTest("GameBoardTestSuiteS30");
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("executing step \'call Move7(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 0);
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.Comment("executing step \'call Move8(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(0, 1);
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("executing step \'call Move9(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move9(1, 1);
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Comment("checking step \'return Move9\'");
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S49
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS49() {
            this.Manager.BeginTest("GameBoardTestSuiteS49");
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S58\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S59\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S60\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S61\'");
            this.Manager.Comment("executing step \'call Move7(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(0, 1);
            this.Manager.Comment("reaching state \'S62\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S63\'");
            this.Manager.Comment("executing step \'call Move8(1,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 0);
            this.Manager.Comment("reaching state \'S64\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S65\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S66
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS66() {
            this.Manager.BeginTest("GameBoardTestSuiteS66");
            this.Manager.Comment("reaching state \'S66\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S67\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S68\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S69\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S70\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S71\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S72\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S73\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S74\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S75\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S76\'");
            this.Manager.Comment("executing step \'call Move6(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(1, 2);
            this.Manager.Comment("reaching state \'S77\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S78\'");
            this.Manager.Comment("executing step \'call Move7(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(0, 1);
            this.Manager.Comment("reaching state \'S79\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S80\'");
            this.Manager.Comment("executing step \'call Move8(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move8(1, 1);
            this.Manager.Comment("reaching state \'S81\'");
            this.Manager.Comment("checking step \'return Move8\'");
            this.Manager.Comment("reaching state \'S82\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S83
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS83() {
            this.Manager.BeginTest("GameBoardTestSuiteS83");
            this.Manager.Comment("reaching state \'S83\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S84\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S85\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S86\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S87\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S88\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S89\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S90\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S91\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S92\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S93\'");
            this.Manager.Comment("executing step \'call Move6(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(0, 1);
            this.Manager.Comment("reaching state \'S94\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S95\'");
            this.Manager.Comment("executing step \'call Move7(1,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 2);
            this.Manager.Comment("reaching state \'S96\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S97\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S98
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GameBoardTestSuiteS98() {
            this.Manager.BeginTest("GameBoardTestSuiteS98");
            this.Manager.Comment("reaching state \'S98\'");
            this.Manager.Comment("executing step \'call Move1(2,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move1(2, 1);
            this.Manager.Comment("reaching state \'S99\'");
            this.Manager.Comment("checking step \'return Move1\'");
            this.Manager.Comment("reaching state \'S100\'");
            this.Manager.Comment("executing step \'call Move2(2,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move2(2, 0);
            this.Manager.Comment("reaching state \'S101\'");
            this.Manager.Comment("checking step \'return Move2\'");
            this.Manager.Comment("reaching state \'S102\'");
            this.Manager.Comment("executing step \'call Move3(0,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move3(0, 2);
            this.Manager.Comment("reaching state \'S103\'");
            this.Manager.Comment("checking step \'return Move3\'");
            this.Manager.Comment("reaching state \'S104\'");
            this.Manager.Comment("executing step \'call Move4(0,0)\'");
            TicTacToeMBT.Implementation.Accumulator.Move4(0, 0);
            this.Manager.Comment("reaching state \'S105\'");
            this.Manager.Comment("checking step \'return Move4\'");
            this.Manager.Comment("reaching state \'S106\'");
            this.Manager.Comment("executing step \'call Move5(2,2)\'");
            TicTacToeMBT.Implementation.Accumulator.Move5(2, 2);
            this.Manager.Comment("reaching state \'S107\'");
            this.Manager.Comment("checking step \'return Move5\'");
            this.Manager.Comment("reaching state \'S108\'");
            this.Manager.Comment("executing step \'call Move6(0,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move6(0, 1);
            this.Manager.Comment("reaching state \'S109\'");
            this.Manager.Comment("checking step \'return Move6\'");
            this.Manager.Comment("reaching state \'S110\'");
            this.Manager.Comment("executing step \'call Move7(1,1)\'");
            TicTacToeMBT.Implementation.Accumulator.Move7(1, 1);
            this.Manager.Comment("reaching state \'S111\'");
            this.Manager.Comment("checking step \'return Move7\'");
            this.Manager.Comment("reaching state \'S112\'");
            this.Manager.EndTest();
        }
        #endregion
         * */
    }
}
